### ISSUE TITLE
utf8 decoding crash

### ISSUE THREAD

**Issue by ethercrow** [jaraco/irc#84] opened 2016-02-17 09:49 UTC
A simple bot crashed while sitting in #haskell@freenode

```
  File "/usr/lib/python2.7/site-packages/irc/bot.py", line 264, in start
    super(SingleServerIRCBot, self).start()
  File "/usr/lib/python2.7/site-packages/irc/client.py", line 1249, in start
    self.reactor.process_forever()
  File "/usr/lib/python2.7/site-packages/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "/usr/lib/python2.7/site-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/usr/lib/python2.7/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/usr/lib/python2.7/site-packages/irc/client.py", line 579, in process_data
    for line in self.buffer:
  File "/usr/lib/python2.7/site-packages/irc/buffer.py", line 104, in lines
    self.handle_exception()
  File "/usr/lib/python2.7/site-packages/irc/buffer.py", line 102, in lines
    yield line.decode(self.encoding, self.errors)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9a in position 101: invalid start byte
```

**Comment by jaraco** [comment] 2016-02-17 16:58
Please read the readme. Duplicate of #40.

**Closed as completed by jaraco** 2016-02-17 16:58 UTC
Labels: duplicate, wontfix
